### ISSUE TITLE
After syncing, jsonrpc method `eth_gettransactionbyhash` not able to find the transaction

### ISSUE THREAD

**Issue by ParthBarot-BoTreeConsulting** [ethereum/ropsten#20]
I use the following command to run geth with testnet, as per the docs it finishes syncing and able to show the balance properly. But, when I am trying to find the transaction by hash, it returns null.

```  
sudo /usr/bin/geth --testnet --verbosity 3 --rpc  --light --rpcaddr=0.0.0.0 --rpcport=8545 --rpcapi eth,personal,net,web3,db
```

The last line synced shows,

``` log
INFO [02-28|18:22:30] Imported new block headers               count=2 elapsed=5.514ms   number=2742610 hash=5fc97f…b0dc77 ignored=0
```

The following returns null

``` 
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getTransactionByHash","params":["MY_TX_HASH_HERE"],"id":1}' http://127.0.0.1  -H "Content-Type: application/json"
```

It returns with,

``` json
{"jsonrpc":"2.0","id":1,"result":null}
```

Any suggestions?

**Comment by ParthBarot-BoTreeConsulting** [comment]
I am not working on this one since a few days now, you may close it if you want OR keep open if someone else faces the same issue then would be helpful to them.

Thanks

**Comment by pdagrawal** [comment]
Hi @shouton , I am facing the same issue. I am able to get that transaction in the block but when I am trying to get it by 'eth_getTransactionByHash' it returns nil. Did you get any solution for this. Please let me know.
