### ISSUE TITLE
When does the sync end? 

### ISSUE THREAD

**Issue by SiddharthMalhotra** [ethereum/ropsten#22]
<img width="1322" alt="screen shot 2018-03-31 at 5 21 07 am" src="https://user-images.githubusercontent.com/4989369/38148729-5f2c5fd0-34a3-11e8-9d0d-77a763f00798.png">

Its been over 2 days since I've been syncing. How does the Ropsten Testnet sync end? 
What is the way to confirm this? 

Also, please guide on what are the next steps for developing applications post the sync, i.e. how can we utilize this sync for development purposes?

**Comment by Gujjar95** [comment]
Yes same thing happened with me too .
