### ISSUE TITLE
Ropsten valid Node

### ISSUE THREAD

**Issue by brunokenj** [ethereum/ropsten#33]
Hi, I'm having problems to connect in the right testnet ropsten chain. Anyone can share some valid nodes? I tried the nodes of ropsten readme (--nodiscover, addNode..) but unsuccessful and even with --testnet only.

VERSION:
   1.8.16-stable-477eb093

geth --testnet --rpc --syncmode "full"

geth --testnet attach

> eth.syncing
{
  currentBlock: 3418706,
  highestBlock: 3418716,
  knownStates: 0,
  pulledStates: 0,
  startingBlock: 3418706
}

peers: [{
      caps: ["eth/62", "eth/63", "par/1", "par/2", "par/3", "pip/1"],
      id: "36af4d9f8785ee1bc3d8c04eb76bbb705a8b08fc044ef4ffb416808ab3680e18c69e0bda10e25b79920d8e582f8ec65918a223d81efc3330565fc899ae5ecdf9",
      name: "Parity-Ethereum/v2.0.6-stable-549e202-20180919/x86_64-linux-gnu/rustc1.29.0",
      network: {
        inbound: false,
        localAddress: "172.31.20.196:47694",
        remoteAddress: "35.174.48.76:30303",
        static: false,
        trusted: false
      },
      protocols: {
        eth: {...}
      }
  }, {
      caps: ["eth/62", "eth/63"],
      id: "566009e2787aaabe68012dd63bad920a2eb32b0dedea7b0596635fe3e687a1a0971322a436725d7de93c2bf9005499e9cc898c824cdd40ba5d7e579a54afd40c",
      name: "Geth/v1.8.16-stable-477eb093/linux-amd64/go1.10.1",
      network: {
        inbound: false,
        localAddress: "172.31.20.196:39256",
        remoteAddress: "35.178.193.227:30303",
        static: false,
        trusted: false
      },
      protocols: {
        eth: {...}
      }
  }, {
      caps: ["eth/63"],
      id: "744316f39e9cb1e5e7013e802731d1e9362a51f6e1030781953b98aae088ce0651f0add5954516c519758a813e705bed127fa933c0d3c0ab970e8ccfab5a2706",
      name: "Geth/v1.8.16-stable-477eb093/linux-amd64/go1.10",
      network: {
        inbound: false,
        localAddress: "172.31.20.196:39522",
        remoteAddress: "47.75.156.101:30303",
        static: false,
        trusted: false
      },
      protocols: {
        eth: {...}
      }
  }],

[3313]: WARN [10-08|12:35:41.551] Ancestor below allowance                 peer=7ab83cadce8b5f82 number=3328706 hash=000000…000000 allowance=3328706
[3313]: WARN [10-08|12:35:41.551] Synchronisation failed, dropping peer    peer=7ab83cadce8b5f82 err="retrieved ancestor is invalid"
[3313]: INFO [10-08|13:02:21.854] Regenerated local transaction journal    transactions=0 accounts=0
[3313]: WARN [10-08|13:13:14.812] Synchronisation failed, dropping peer    peer=865a63255b3bb680 err="action from bad peer ignored"

**Comment by enVolt** [comment]
Did you find anything?
