### ISSUE TITLE
Best way to get a semi large amount of rETH without mining?

### ISSUE THREAD

**Issue by hugoroussel** [ethereum/ropsten#40]
Hello for an application of mine I would need a semi-large amount of ropsten ether (50-100). What would be the best way to go about it? The faucet only drips 0.3 eth an hour. Thanks in advance.

**Comment by hugoroussel** [comment]
Leaving this as a reference: https://faucet.dimensions.network. If you email them they will send larger amounts too.

**Comment by bo-liu** [comment]
I also need a semi-large amount of ropsten ether (50-100) for our testnet. What would be the best way to go about it? The https://faucet.dimensions.network/ is down. @hugoroussel Do you happen to have some ropsten ether left? My address 0x5cd293a257ad7d6E37DA47547b4a860665Bbb562
