### ISSUE TITLE
faucet offline

### ISSUE THREAD

**Issue by drandreaskrueger** [ethereum/ropsten#7]
```
curl http://faucet.ropsten.be:3001/donate/0x7....
curl: (7) Failed to connect to faucet.ropsten.be port 3001: Connection refused
```

http://faucet.ropsten.be:3001/  
This site can’t be reached - faucet.ropsten.be refused to connect.

**Comment by Ollemesh** [comment]
The same

**Comment by Ollemesh** [comment]
You can get testnet ropsten coins using metamask https://metamask.io/
I have to install chrome plugin

**Comment by drandreaskrueger** [comment]
> You can get testnet ropsten coins using metamask

How?   
Yes, I have installed metamask now.  

0xF73Fc2904CEadF5BDbDF5A65F0f1958fAD10d731
